[package]
name = "gossip"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.80"
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.114"
tokio = {version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"]}
